### ISSUE TITLE
Could not find gem 'khipu-api-ruby-client (>= 0) ruby' in git://github.com/khipu/khipu-api-ruby-client.git (at master).

### ISSUE THREAD

**Issue by nelyj** [khipu/khipu-api-ruby-client#2]
Este error aparece cuando intento agregarla a mi proyecto en Rails:

Could not find gem 'khipu-api-ruby-client (>= 0) ruby' in git://github.com/khipu/khipu-api-ruby-client.git (at master). Source does not contain any versions of 'khipu-api-ruby-client (>= 0) ruby'

Si la instalo directo por consola no tengo problema, sólo ocurre cuando lo agrego al Gemfile

**Comment by edavism** [comment]
Hola, el nombre de la gema es khipu-api-client no khipu-api-ruby-client, el nombre del repositorio agrega el lenguaje para no colisionar entre los clientes, pero a nivel de gema o maven o composer no es necesario agregarlo.
