### ISSUE TITLE
Bundler could not find compatible versions for gem "typhoeus" v. 1.3.0

### ISSUE THREAD

**Issue by saheredia** [khipu/khipu-api-ruby-client#9]
Incorporo en mi Gemfile:

      gem 'khipu-api-client', '2.7.1'
      gem 'typhoeus', '1.3.0'

Sin embargo genera el siguiente error al usar el comando : bundle install

Bundler could not find compatible versions for gem "typhoeus":
```
  In Gemfile:
    typhoeus (= 1.3.0)

    khipu-api-client (= 2.7.1) was resolved to 2.7.1, which depends on
      typhoeus (>= 0.2.1, ~> 0.2)
```
Solicitando una version del typhoeus que no es posible instalar

**Comment by edavism** [comment]
Hola, actualizamos las dependencias (no solo typhoeus), la gema versión 2.7.2 incluye esto.
